name: Patient Indexer Quality Check
run-name: ${{ github.head_ref }} quality control
on:
  pull_request: 
    branches:
      - bst_assignment
jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup requirements
        run: sudo apt-get -y --no-install-recommends install clang-format clang-tidy
      
      - name: Code style check
        run: |
          find ./src -name "*.c" | xargs clang-format --dry-run --Werror
          find ./include -name "*.h" | xargs clang-format --dry-run --Werror

      - name: Code lint check
        run: |
          clang-tidy $(find ./src -name "*.c") -- -Iinclude/ -Iinclude/PatientIndexer -Iinclude/SparseMatrix
          clang-tidy $(find ./include -name "*.h")
  build:
    needs: static-check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Build PatientIndexer project
        run: make indexer
    
      - name: Build PatientIndexer test runner
        run: make indexer-test

      - name: Save test artifact
        uses: actions/upload-artifact@v6
        with:
          name: PatientIndexerTestRunner
          path: bin/PatientIndexerTest
  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Get test artifact
          uses: actions/download-artifact@v4
          with:
            name: PatientIndexerTestRunner
            path: bin/

        - name: Run test artifact
          run: |
            chmod +x bin/PatientIndexerTest
            bin/PatientIndexerTest